import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { asBoolean } from "@paperclipai/adapter-utils/server-utils";

type PreparedOpenCodeRuntimeConfig = {
  env: Record<string, string>;
  notes: string[];
  credsFilePath: string | null;
  runtimeConfigDir: string | null;
  cleanup: () => Promise<void>;
};

// OpenCode's Bash tool sanitizes its environment and strips custom vars like
// PAPERCLIP_* before invoking commands. To get per-run credentials to the
// agent's shell, we write them to a file the agent can `source` at the top of
// each bash invocation. See spec 2026-06-11-opencode-paperclip-creds-fix-spec.md.
const PAPERCLIP_CREDS_FILENAME = "paperclip-run.env";
const PAPERCLIP_ENV_PREFIX = "PAPERCLIP_";
const PAPERCLIP_EXTRA_ENV_KEYS = ["AGENT_HOME"] as const;

// Headless permission defaults injected when `dangerouslySkipPermissions` is on
// (default true). User-supplied permission keys win — we only fill in defaults
// for keys the user did not set.
const DEFAULT_HEADLESS_PERMISSIONS: Record<string, string> = {
  bash: "allow",
  edit: "allow",
  read: "allow",
  write: "allow",
  webfetch: "allow",
  external_directory: "allow",
};

function resolveXdgConfigHome(env: Record<string, string>): string {
  return (
    (typeof env.XDG_CONFIG_HOME === "string" && env.XDG_CONFIG_HOME.trim()) ||
    (typeof process.env.XDG_CONFIG_HOME === "string" && process.env.XDG_CONFIG_HOME.trim()) ||
    path.join(os.homedir(), ".config")
  );
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function readJsonObject(filepath: string): Promise<Record<string, unknown>> {
  try {
    const raw = await fs.readFile(filepath, "utf8");
    const parsed = JSON.parse(raw);
    return isPlainObject(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

function shellQuoteSingle(value: string): string {
  // POSIX-safe single-quote: close, escape, reopen.
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function collectPaperclipCredsVars(env: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(env)) {
    if (typeof value !== "string") continue;
    if (key.startsWith(PAPERCLIP_ENV_PREFIX) || (PAPERCLIP_EXTRA_ENV_KEYS as readonly string[]).includes(key)) {
      out[key] = value;
    }
  }
  return out;
}

function buildCredsFileContents(vars: Record<string, string>): string {
  const lines: string[] = [
    "# Paperclip per-run credentials. Source before any Paperclip API call.",
    "# Generated by @paperclipai/adapter-opencode-local; do not commit.",
  ];
  for (const key of Object.keys(vars).sort()) {
    lines.push(`export ${key}=${shellQuoteSingle(vars[key])}`);
  }
  return `${lines.join("\n")}\n`;
}

async function writeCredsFile(credsFilePath: string, vars: Record<string, string>): Promise<void> {
  await fs.writeFile(credsFilePath, buildCredsFileContents(vars), { mode: 0o600 });
  // Belt and suspenders: some platforms ignore the mode arg on writeFile.
  try {
    await fs.chmod(credsFilePath, 0o600);
  } catch {
    // best-effort
  }
}

export async function prepareOpenCodeRuntimeConfig(input: {
  env: Record<string, string>;
  config: Record<string, unknown>;
}): Promise<PreparedOpenCodeRuntimeConfig> {
  const skipPermissions = asBoolean(input.config.dangerouslySkipPermissions, true);

  const runtimeConfigHome = await fs.mkdtemp(path.join(os.tmpdir(), "paperclip-opencode-config-"));
  const cleanup = async () => {
    await fs.rm(runtimeConfigHome, { recursive: true, force: true });
  };

  // PRIMARY fix: write the per-run Paperclip credentials to a 0600 file in the
  // temp dir. The opencode-local prompt prefix points the agent at this file
  // so it can `source` it inside its sandboxed bash.
  const credsVars = collectPaperclipCredsVars(input.env);
  const credsFilePath = path.join(runtimeConfigHome, PAPERCLIP_CREDS_FILENAME);
  await writeCredsFile(credsFilePath, credsVars);

  const credsNote = `Wrote per-run Paperclip credentials to ${credsFilePath} (mode 0600, ${Object.keys(credsVars).length} vars). Prompt prefix instructs the agent to \`source\` it before any API call.`;

  if (!skipPermissions) {
    return {
      env: { ...input.env },
      notes: [credsNote],
      credsFilePath,
      runtimeConfigDir: null,
      cleanup,
    };
  }

  const sourceConfigDir = path.join(resolveXdgConfigHome(input.env), "opencode");
  const runtimeConfigDir = path.join(runtimeConfigHome, "opencode");
  const runtimeConfigPath = path.join(runtimeConfigDir, "opencode.json");

  await fs.mkdir(runtimeConfigDir, { recursive: true });
  try {
    await fs.cp(sourceConfigDir, runtimeConfigDir, {
      recursive: true,
      force: true,
      errorOnExist: false,
      dereference: false,
    });
  } catch (err) {
    if ((err as NodeJS.ErrnoException | null)?.code !== "ENOENT") {
      throw err;
    }
  }

  const existingConfig = await readJsonObject(runtimeConfigPath);
  const existingPermission = isPlainObject(existingConfig.permission)
    ? existingConfig.permission
    : {};
  const nextPermission: Record<string, unknown> = { ...existingPermission };
  const filledDefaults: string[] = [];
  for (const [key, value] of Object.entries(DEFAULT_HEADLESS_PERMISSIONS)) {
    if (!(key in nextPermission)) {
      nextPermission[key] = value;
      filledDefaults.push(key);
    }
  }
  const nextConfig = {
    ...existingConfig,
    permission: nextPermission,
  };
  await fs.writeFile(runtimeConfigPath, `${JSON.stringify(nextConfig, null, 2)}\n`, "utf8");

  const permissionNote =
    filledDefaults.length > 0
      ? `Injected headless OpenCode permission defaults (${filledDefaults.join(", ")}); user-set keys preserved.`
      : "OpenCode permission block already covered all headless defaults; no overrides applied.";

  return {
    env: {
      ...input.env,
      XDG_CONFIG_HOME: runtimeConfigHome,
    },
    notes: [credsNote, permissionNote],
    credsFilePath,
    runtimeConfigDir,
    cleanup,
  };
}
